name: CICD

on:
  push:
    branches:
      - 'main'
jobs:
  config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  
  Publish:
    steps:
    - name: Configure docker for GCP
      if: |
        !cancelled() && needs.config.result == 'success' 
      run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

    - name: Build docker image - api
      if: |
        !cancelled() && needs.config.result == 'success' 
      run:  |
       cd api
       docker build . -t europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/web-appplication/api-app:latest
       
    - name: Push to Google Artifact Registry
      if: |
        !cancelled() && needs.config.result == 'success' 
      run:  docker push europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/web-appplication/api-app:latest